### ISSUE TITLE
Importing arrays of ref

### ISSUE THREAD

**Issue by victormithouard** [fauna/faunadb-importer#44]
Hi

We are looking to import csv with arrays of refs, is there a way to do this with the importer?

Examples code with a ref to another file - ref is currently a single ref but we have records which have multiple refs.

```
data/test1.csv:
  class: test1
  fields:
    - name: id
      type: ref

    - name: name
      type: string

  ignoredFields:
    - id

data/test2.csv:
  class: test2
  fields:
    - name: user_id
      type: ref(test1) # We would like this to be an array of brands
```

Thank you in advance!
